---
apiVersion: v1
kind: Service
metadata:
  name: service-hello
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    name: k8smaestro-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  selector:
    matchLabels:
      name: k8smaestro-webapp
  replicas: 3
  strategy:
    type: RollingUpdate # update strategy (default)
  template:
    metadata:
      labels:
        name: k8smaestro-webapp
    spec:
      containers:
        - name: webapp-ctr
          image: dockerbogo/docker-nginx-hello-world:latest
          ports:
            - containerPort: 80