apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: game-2048
spec:
  hard:
    pods: "10" # maximum number of pods
    requests.cpu: "2"
    requests.memory: 2Gi # request: Sum of CPU
    limits.cpu: "2"
    limits.memory: 2Gi # limit: Sum of memory
---